apiVersion: v1
kind: Service
metadata:
  name: {{ include "tetris.fullname" . }}
  labels:
    {{- include "tetris.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      nodePort: {{.Values.service.nodePort }}
      protocol: TCP
      name: http
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "tetris.selectorLabels" . | nindent 4 }}
